# Stage template: RG Permissions (no top-level `stages:` key)

parameters:
  run_mode: 'ByCustodian'          # ByCustodian | AllADH
  adh_group: ''
  adh_subscription_type: ''        # prd | nonprd
  prodCsvPath: ''
  nonProdCsvPath: ''
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/rg-perms'
  branchName: ''
  poolType: 'self'                 # hosted | self
  poolName: ''                     # leave blank to auto-compute in job template if you use that
  poolSuffix: '_agent1'            # _agent1 | _agent2
  useDemands: true

- stage: RG_Permissions
  displayName: RG Permissions
  variables:
    outDir: ${{ parameters.outDir }}

  jobs:
  # ---------- ByCustodian ----------
  - ${{ if eq(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions – ByCustodian'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-ByCustodian.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -adh_group "${{ parameters.adh_group }}" -OutputDir "$(outDir)" -BranchName "$(Build.SourceBranchName)"
        artifactName: 'rg-perms'
        publishPath: '$(outDir)'

        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        poolSuffix: ${{ parameters.poolSuffix }}
        adh_group: ${{ parameters.adh_group }}
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        useDemands: ${{ parameters.useDemands }}

  # ---------- AllADH ----------
  - ${{ if ne(parameters.run_mode, 'ByCustodian') }}:
    - template: ../templates/job.powershell-with-az.yml
      parameters:
        variableGroup: ${{ parameters.variableGroup }}
        displayName: 'RG Permissions – AllADH'
        scriptPath: 'sanitychecks/scripts/Scan-RG-Permissions-AllADH.ps1'
        workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
        arguments: >
          -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
          -ProdCsvPath "${{ parameters.prodCsvPath }}" -NonProdCsvPath "${{ parameters.nonProdCsvPath }}"
          -OutputDir "$(outDir)" -BranchName "$(Build.SourceBranchName)"
        artifactName: 'rg-perms-ALLADH'
        publishPath: '$(outDir)'

        poolType: ${{ parameters.poolType }}
        poolName: ${{ parameters.poolName }}
        poolSuffix: ${{ parameters.poolSuffix }}
        # not used for AllADH, but harmless if passed
        adh_group: ''
        adh_subscription_type: ${{ parameters.adh_subscription_type }}
        useDemands: false
