trigger: none
pool: { vmImage: 'windows-latest' }

parameters:
- name: adh_group
  type: string
  default: 'ADHCSM'
- name: adh_subscription_type
  type: string
  default: 'nonprd'
  values: [ 'nonprd', 'prd' ]
- name: includeValues
  type: boolean
  default: true
- name: filePath
  type: string
  default: '$(System.DefaultWorkingDirectory)/Modernization_Terraform/sanitychecks/resource_sanitychecks.xlx'

variables:
- group: modernization_terraform_subscription_details
- group: test_modernization_terraform_subscription_details
- group: modernization_tfstate_backend_details

stages:
- stage: KVSecrets
  displayName: "KV Secrets scan"
  jobs:
  - job: RunKVSecrets
    steps:
    - checkout: self
      persistCredentials: true
      clean: false

    - task: PowerShell@2
      displayName: "Scan Key Vault secrets"
      inputs:
        targetType: filePath
        filePath: '$(System.DefaultWorkingDirectory)/Modernization_Terraform/sanitychecks/scan-kv-secrets.ps1'
        arguments: >
          -adh_group "${{ parameters.adh_group }}"
          -adh_subscription_type "${{ parameters.adh_subscription_type }}"
          -FilePath "${{ parameters.filePath }}"
          -IncludeSecretValues ${{ parameters.includeValues }}
        pwsh: true
      env:
        # SPN creds come from variable groups above:
        client_id: $(client_id)
        client_secret: $(client_secret)
        # Optional: if your org requires tenant for SPN login, uncomment next line
        # tenant_id: $(tenant_id)

    - task: PublishBuildArtifacts@1
      displayName: "Publish 'kv-scan' artifact"
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/Modernization_Terraform/sanitychecks/kv-scan'
        ArtifactName: 'kv-scan'
        publishLocation: 'Container'
