parameters:
  - name: manual
    type: boolean
    default: false
  - name: adh_group
    type: string
  - name: adh_subscription_type
    type: string
  - name: filePath      # this is already an absolute path from pipeline.yml
    type: string
  - name: includeValues
    type: boolean
    default: true

stages:
- stage: KVSecrets
  displayName: "KV Secrets sanity check"
  jobs:
  - template: ../templates/job.scan.ps1.yml
    parameters:
      displayName: "Scan Key Vault secrets"
      scriptPath: '$(System.DefaultWorkingDirectory)/Modernization_Terraform/sanitychecks/scan-kv-secrets.ps1'
      scriptArgs: >
        -adh_group "${{ parameters.adh_group }}"
        -adh_subscription_type "${{ parameters.adh_subscription_type }}"
        -FilePath "${{ parameters.filePath }}"
        -IncludeSecretValues ${{ parameters.includeValues }}
      artifactFolder: 'kv-scan'
      manual: ${{ parameters.manual }}
      envVars:
        client_id: $(client_id)
        client_secret: $(client_secret)
        # tenant_id: $(tenant_id)   # only if your org requires tenant for SPN login
