parameters:
  run_mode: 'ByCustodian'
  adh_group: ''
  secretsCsvPath: '$(Build.SourcesDirectory)/sanitychecks/inputs/kvsecretsscan.csv'
  variableGroup: 'modernization_tfstate_backend_details'
  outDir: '$(Build.ArtifactStagingDirectory)/kv-secrets'

stages:
- stage: KV_Secrets
  displayName: KV Secrets (${{ parameters.run_mode }} ${{ parameters.adh_group }})
  jobs:
  - template: ../templates/job.powershell-with-az.yml
    parameters:
      variableGroup: ${{ parameters.variableGroup }}
      displayName: 'KV Secrets Scan'
      scriptPath: ${{ if eq(parameters.run_mode, 'ByCustodian') }} 'sanitychecks/scripts/Scan-KV-Secrets-ByCustodian.ps1' ${{ else }} 'sanitychecks/scripts/Scan-KV-Secrets-AllADH.ps1' ${{ end }}
      workingDir: '$(Build.SourcesDirectory)/sanitychecks/scripts'
      arguments: >
        -TenantId "$(tenant_id)" -ClientId "$(backend_client_id)" -ClientSecret "$(backend_client_secret)"
        -SecretCsvPath "${{ parameters.secretsCsvPath }}"
        ${{ if eq(parameters.run_mode, 'ByCustodian') }} -adh_group "${{ parameters.adh_group }}" ${{ end }}
        -OutputDir "$(Build.ArtifactStagingDirectory)/kv-secrets"
      artifactName: 'kv-secrets'
      publishPath: "$(Build.ArtifactStagingDirectory)/kv-secrets"
