trigger: none

parameters:
- name: run_mode
  displayName: Run mode
  type: string
  default: ByCustodian
  values: [ ByCustodian, AllADH ]
- name: adh_group
  displayName: Custodian (when ByCustodian)
  type: string
  default: ''

# (Keep your Validate stage here if you have it)

# --- RG stages (you already have) ---
- template: stages/rg-permissions.stage.yml
  parameters:
    adh_group: ${{ parameters.adh_group }}
    prodCsvPath: '$(Build.SourcesDirectory)/sanitychecks/inputs/prod_permissions.csv'
    nonProdCsvPath: '$(Build.SourcesDirectory)/sanitychecks/inputs/nonprod_permissions.csv'
    variableGroup: 'modernization_tfstate_backend_details'
    outDir: '$(Build.ArtifactStagingDirectory)/rg-perms-${{ parameters.adh_group }}'

- template: stages/rg-tags.stage.yml
  parameters:
    adh_group: ${{ parameters.adh_group }}
    variableGroup: 'modernization_tfstate_backend_details'
    outDir: '$(Build.ArtifactStagingDirectory)/rg-tags-${{ parameters.adh_group }}'

# --- KV Secrets ---
- template: stages/kv-secrets.stage.yml
  parameters:
    run_mode: ${{ parameters.run_mode }}
    adh_group: ${{ parameters.adh_group }}
    secretsCsvPath: '$(Build.SourcesDirectory)/sanitychecks/inputs/kvsecretscan.csv'
    variableGroup: 'modernization_tfstate_backend_details'
    outDir: ${{ if eq(parameters.run_mode, 'ByCustodian') }} '$(Build.ArtifactStagingDirectory)/kv-secrets-${{ parameters.adh_group }}' ${{ else }} '$(Build.ArtifactStagingDirectory)/kv-secrets-ALLADH' ${{ end }}

# --- KV Permissions ---
- template: stages/kv-permissions.stage.yml
  parameters:
    run_mode: ${{ parameters.run_mode }}
    adh_group: ${{ parameters.adh_group }}
    variableGroup: 'modernization_tfstate_backend_details'
    outDir: ${{ if eq(parameters.run_mode, 'ByCustodian') }} '$(Build.ArtifactStagingDirectory)/kv-perms-${{ parameters.adh_group }}' ${{ else }} '$(Build.ArtifactStagingDirectory)/kv-perms-ALLADH' ${{ end }}

# --- KV Firewall / Networks ---
- template: stages/kv-firewall.stage.yml
  parameters:
    run_mode: ${{ parameters.run_mode }}
    adh_group: ${{ parameters.adh_group }}
    variableGroup: 'modernization_tfstate_backend_details'
    outDir: ${{ if eq(parameters.run_mode, 'ByCustodian') }} '$(Build.ArtifactStagingDirectory)/kv-firewall-${{ parameters.adh_group }}' ${{ else }} '$(Build.ArtifactStagingDirectory)/kv-firewall-ALLADH' ${{ end }}
